function Hd = CustomBandpassFilter(N,Fc1,Fc2,Fs)
    %EKSEMPEL_L14_BPF_FILTERDESIGNER Returns a discrete-time filter object.

    % MATLAB Code
    % Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
    % Generated on: 07-Dec-2020 15:33:17

    % Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

    % % All frequency values are in Hz.
    % Fs = 8000; % Sampling Frequency

    % N = 4; % Order
    % Fc1 = 2000; % First Cutoff Frequency
    % Fc2 = 3000; % Second Cutoff Frequency

    % Construct an FDESIGN object and call its BUTTER method.
    h = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
    Hd = design(h, 'butter');

    % [EOF]
